In [ ]:
import json
import ast
import pandas as pd

In [22]:
import requests
# Function to download files from NOMAD upload
def download_archive(upload_id: str = '8UcL8cCSSYa6sgmhQVXhaQ', file_name='cost_perla_09_06_2026.json'):
    res = requests.get(
        f'https://nomad-lab.eu/prod/v1/api/v1/uploads/{upload_id}/raw/{file_name}?offset=0&length=-1&decompress=false&ignore_mime_type=false&compress=false',
        headers={
            'Accept': 'application/octet-stream',
        },
        timeout=120,
    )
    res.raise_for_status()
    with open(f'{file_name}','wb') as fp:
        fp.write(res.content)
    print("File saved successfully!")

In [24]:
download_archive(file_name='cost_perla_09_06_2026.json')

File saved successfully!

In [15]:
costs_json=json.load(open('cost_perla_09_06_2026.json','r'))
dois=list(costs_json)

In [17]:
costs={i:{'raw_gen_ai_request':[],'litellm_request':[],'Perla Extract - LLM Call Cost':[]} for i in dois}
for doi in dois:
    for trace in costs_json[doi]:
        cost=None
        if trace['type']=='SPAN' and trace['name']=='raw_gen_ai_request':
            cost=ast.literal_eval(trace['metadata']['attributes.llm.anthropic.usage'])
            cost={'input':cost['input_tokens'],'output':cost['output_tokens'],'total':cost['output_tokens']+cost['input_tokens']}
        if trace['type']=='GENERATION' and trace['name']=='litellm_request':
            cost={'usage':trace.get('usageDetails'),'cost':trace.get('costDetails')}
            cost['usage']={k:int(v) for k,v in cost['usage'].items()}
        else:
            try:
                a=json.loads(trace['output'])
                cost={'usage':a.get('usage'),'cost':a.get('costDetails')}
            except:
                pass
        costs[doi][trace['name']].append({'id':trace.get('id'),
                           'parentId':trace.get('parentObservationId'),
                           'type':trace['name'],
                           'cost':cost,
                          'startTime':trace.get('startTime')})
    for i in costs[doi]:
        costs[doi][i]=sorted(costs[doi][i],key=lambda x: x['startTime'])
    if costs[doi]['Perla Extract - LLM Call Cost'][0]['cost'] is None:
        costs[doi]['Perla Extract - LLM Call Cost'][0]['cost']=costs[doi]['litellm_request'][-1]['cost']

In [ ]:
df=[]
for doi, c in costs.items():
    m={'retries':len(c['raw_gen_ai_request'])-1,
    'total_usage':c['Perla Extract - LLM Call Cost'][0]['cost']['usage'],
    'total_cost':c['Perla Extract - LLM Call Cost'][0]['cost']['cost'],
    'usage':[i['cost'] for i in c['raw_gen_ai_request']]}
    dfm={'doi':doi,'retries':len(c['raw_gen_ai_request'])-1}
    dfm.update({f'{k}_tokens':v for k,v in m['total_usage'].items()})
    dfm.update({f'{k}_cost':v for k,v in m['total_cost'].items()})
    for i,c_i in enumerate(m['usage']):
        dfm.update({f'call_{i}_{k}_tokens':v for k,v in c_i.items()})
    df.append(dfm)
df=pd.DataFrame(df).fillna(0)

In [19]:
df

,doi,retries,input_tokens,output_tokens,total_tokens,input_cost,output_cost,total_cost,call_0_input_tokens,call_0_output_tokens,call_0_total_tokens,call_1_input_tokens,call_1_output_tokens,call_1_total_tokens
0,10.1038/s41467-023-36141-8,1,76227,4821,81048,0.228681,0.072315,0.300996,34916,2411,37327,41311.0,2410.0,43721.0
1,10.1002/adfm.202212698,0,32406,5335,37741,0.097218,0.080025,0.177243,32406,5335,37741,0.0,0.0,0.0
2,10.1016/j.jmst.2021.03.045,0,27648,4782,32430,0.082944,0.071730,0.154674,27648,4782,32430,0.0,0.0,0.0
3,10.1021/acsaelm.4c02297,0,31471,2407,33878,0.094413,0.036105,0.130518,31471,2407,33878,0.0,0.0,0.0
4,10.1016/j.matlet.2016.07.004,0,18570,6099,24669,0.055710,0.091485,0.147195,18570,6099,24669,0.0,0.0,0.0
5,10.1038/s41560-022-01102-w,0,32782,5131,37913,0.098346,0.076965,0.175311,32782,5131,37913,0.0,0.0,0.0
6,10.1002/solr.202100879,1,57623,2518,60141,0.172869,0.037770,0.210639,27476,1483,28959,30147.0,1035.0,31182.0
7,10.1038/s41560-022-01061-2,0,15780,1303,17083,0.047340,0.019545,0.066885,15780,1303,17083,0.0,0.0,0.0
8,10.1002/adfm.201904856,0,27601,6971,34572,0.082803,0.104565,0.187368,27601,6971,34572,0.0,0.0,0.0
9,10.1021/acsaem.9b01928,0,29637,2048,31685,0.088911,0.030720,0.119631,29637,2048,31685,0.0,0.0,0.0
10,10.1016/j.jallcom.2023.170970,0,33534,4002,37536,0.100602,0.060030,0.160632,33534,4002,37536,0.0,0.0,0.0
11,10.1002/solr.202300817,0,30611,5504,36115,0.091833,0.082560,0.174393,30611,5504,36115,0.0,0.0,0.0
12,10.1126/science.adf0194,0,23869,3470,27339,0.071607,0.052050,0.123657,23869,3470,27339,0.0,0.0,0.0
13,10.1038/s41467-020-20272-3,1,72122,6090,78212,0.216366,0.091350,0.307716,33165,3648,36813,38957.0,2442.0,41399.0
14,10.1016/j.nanoen.2016.05.023,0,26236,4803,31039,0.078708,0.072045,0.150753,26236,4803,31039,0.0,0.0,0.0
15,10.1002/adma.202302143,0,35478,2989,38467,0.106434,0.044835,0.151269,35478,2989,38467,0.0,0.0,0.0
16,10.1038/s41467-021-27740-4,0,39003,9120,48123,0.117009,0.136800,0.253809,39003,9120,48123,0.0,0.0,0.0
17,10.1039/c7nr04692h,0,29256,3540,32796,0.087768,0.053100,0.140868,29256,3540,32796,0.0,0.0,0.0
18,10.1002/adma.202305822,0,29357,4364,33721,0.088071,0.065460,0.153531,29357,4364,33721,0.0,0.0,0.0
19,10.1021/acs.chemmater.8b01521,0,22223,774,22997,0.066669,0.011610,0.078279,22223,774,22997,0.0,0.0,0.0
20,10.1002/adfm.201500335,0,28225,1365,29590,0.084675,0.020475,0.105150,28225,1365,29590,0.0,0.0,0.0
21,10.1039/c5ta00568j,0,17700,710,18410,0.053100,0.010650,0.063750,17700,710,18410,0.0,0.0,0.0
22,10.1002/solr.202300438,0,59249,21569,80818,0.177747,0.323535,0.501282,59249,21569,80818,0.0,0.0,0.0
23,10.1039/c5dt02388b,0,29790,3682,33472,0.089370,0.055230,0.144600,29790,3682,33472,0.0,0.0,0.0
24,10.1021/acsaem.4c02660,0,33658,7558,41216,0.100974,0.113370,0.214344,33658,7558,41216,0.0,0.0,0.0
25,10.1002/solr.201900370,0,25799,3828,29627,0.077397,0.057420,0.134817,25799,3828,29627,0.0,0.0,0.0
26,10.1038/s41563-025-02163-4,0,31936,8200,40136,0.095808,0.123000,0.218808,31936,8200,40136,0.0,0.0,0.0
27,10.1038/nmat4014,1,61599,9419,71018,0.184797,0.141285,0.326082,26409,5708,32117,35190.0,3711.0,38901.0
28,10.1016/j.nanoen.2022.107416,1,56447,4222,60669,0.169341,0.063330,0.232671,25795,2523,28318,30652.0,1699.0,32351.0
29,10.1016/j.matt.2023.09.006,0,37208,4009,41217,0.111624,0.060135,0.171759,37208,4009,41217,0.0,0.0,0.0

In [20]:
agg_df=df[['retries','input_tokens', 'output_tokens', 'total_tokens',
       'input_cost', 'output_cost', 'total_cost']].aggregate(['sum','mean','std']).round(2)

In [21]:
agg_df

,retries,input_tokens,output_tokens,total_tokens,input_cost,output_cost,total_cost
sum,5.00,1073045.00,150633.00,1223678.00,3.22,2.26,5.48
mean,0.17,35768.17,5021.10,40789.27,0.11,0.08,0.18
std,0.38,15611.48,3868.28,17605.63,0.05,0.06,0.09